tools:
  claude:
    name: "Claude Code"
    tasks:
      rules:
        name: "Project Rules from Prompt Library"
        description: "Copy project-specific rules from Lullabot prompt library"
        type: "remote-copy-files"
        link: "https://github.com/Lullabot/prompt_library"
        repository:
          url: "https://github.com/Lullabot/prompt_library"
          type: "branch"
          target: "main"
        source: "{project-type}/rules/"
        target: ".ai/rules"
        required: false
        requires-project: true
        prompt: "Would you like to install project-specific rules from the prompt library?"
      ai-task-manager:
        name: "AI Task Manager"
        description: "Set up AI Task Manager"
        type: "package-install"
        link: "https://github.com/e0ipso/ai-task-manager"
        package:
          name: "@e0ipso/ai-task-manager"
          type: "npx"
          install-command: "npx @e0ipso/ai-task-manager init --assistants claude"
          version-command: "npx @e0ipso/ai-task-manager init --version"
        required: false
        prompt: "Would you like to set up AI Task Manager?"
      agents-md:
        name: "AGENTS.md"
        description: "Create/update AGENTS.md with project-specific rules"
        type: "agents-md"
        source: "assets/AGENTS.md"
        target: "."
        link-type: "@"
        required: false
        prompt: "Would you like to set up AGENTS.md with project-specific rules?"
      wrapper:
        name: "CLAUDE.md Wrapper"
        description: "Create claude.md wrapper file"
        type: "copy-files"
        source: "assets/wrappers/"
        items: { "claude.md": "CLAUDE.md" }
        target: "."
        required: false
        prompt: "Would you like to create a CLAUDE.md wrapper file?"
  cursor:
    name: "Cursor"
    tasks:
      memory-bank:
        name: "Memory Bank Setup"
        description: "Initialize cursor-bank for AI assistance"
        type: "package-install"
        link: "https://github.com/tacticlaunch/cursor-bank"
        package:
          name: "cursor-bank"
          type: "npx"
          install-command: "npx cursor-bank init"
          version-command: "npx cursor-bank --version"
        required: false
        prompt: "Would you like to set up a memory bank for AI assistance?"
      rules:
        name: "Project Rules from Prompt Library"
        description: "Copy project-specific rules from Lullabot prompt library"
        type: "remote-copy-files"
        link: "https://github.com/Lullabot/prompt_library"
        repository:
          url: "https://github.com/Lullabot/prompt_library"
          type: "branch"
          target: "main"
        source: "{project-type}/rules/"
        target: ".ai/rules"
        required: false
        requires-project: true
        prompt: "Would you like to install project-specific rules from the prompt library?"
      drupal-rules:
        name: "Drupal Rules"
        description: "Copy Drupal rules from ivangrynenko/cursorrules"
        type: "remote-copy-files"
        link: "https://github.com/ivangrynenko/cursorrules"
        repository:
          url: "https://github.com/ivangrynenko/cursorrules"
          type: "branch"
          target: "main"
        source: ".cursor/rules/"
        target: ".ai/rules"
        items:
          - "drupal-*.mdc"
          - "*drupal-*.mdc"
        projects: ["development"]
        required: false
        prompt: "Would you like to install Drupal rules from ivangrynenko/cursorrules?"
      agents-md:
        name: "AGENTS.md"
        description: "Create/update AGENTS.md with project-specific rules"
        type: "agents-md"
        source: "assets/AGENTS.md"
        target: "."
        link-type: "@"
        required: false
        prompt: "Would you like to set up AGENTS.md with project-specific rules?"
      vscode-xdebug:
        name: "VSCode XDebug"
        description: "Set up VSCode XDebug for PHP debugging"
        type: "copy-files"
        source: "assets/vscode"
        # Optional: specify individual files/directories to copy
        items: ["launch.json"]
        target: ".vscode/"
        required: false
        prompt: "Would you like to set up VSCode XDebug for PHP debugging?"
  gemini:
    name: "Gemini"
    tasks:
      rules:
        name: "Project Rules from Prompt Library"
        description: "Copy project-specific rules from Lullabot prompt library"
        type: "remote-copy-files"
        link: "https://github.com/Lullabot/prompt_library"
        repository:
          url: "https://github.com/Lullabot/prompt_library"
          type: "branch"
          target: "main"
        source: "{project-type}/rules/"
        target: ".ai/rules"
        required: false
        requires-project: true
        prompt: "Would you like to install project-specific rules from the prompt library?"
      ai-task-manager:
        name: "AI Task Manager"
        description: "Set up AI Task Manager"
        type: "package-install"
        link: "https://github.com/e0ipso/ai-task-manager"
        package:
          name: "@e0ipso/ai-task-manager"
          type: "npx"
          install-command: "npx @e0ipso/ai-task-manager init --assistants gemini"
          version-command: "npx @e0ipso/ai-task-manager init --version"
        required: false
        prompt: "Would you like to set up AI Task Manager?"
      agents-md:
        name: "AGENTS.md"
        description: "Create/update AGENTS.md with project-specific rules"
        type: "agents-md"
        source: "assets/AGENTS.md"
        target: "."
        link-type: "markdown"
        required: false
        prompt: "Would you like to set up AGENTS.md with project-specific rules?"
      wrapper:
        name: "Gemini Wrapper"
        description: "Create Gemini wrapper file"
        type: "copy-files"
        source: "assets/wrappers/"
        items: { "gemini.md": "GEMINI.md" }
        target: "."
        required: false
        prompt: "Would you like to create a Gemini wrapper file?"
  github-copilot:
    name: "GitHub Copilot"
    tasks:
      rules:
        name: "Project Rules from Prompt Library"
        description: "Copy project-specific rules from Lullabot prompt library"
        type: "remote-copy-files"
        repository:
          url: "https://github.com/Lullabot/prompt_library"
          type: "branch"
          target: "main"
        source: "{project-type}/rules/"
        target: ".ai/rules"
        required: false
        requires-project: true
        prompt: "Would you like to install project-specific rules from the prompt library?"
      agents-md:
        name: "AGENTS.md"
        description: "Create/update AGENTS.md with project-specific rules"
        type: "agents-md"
        source: "assets/AGENTS.md"
        target: "."
        link-type: "markdown"
        required: false
        prompt: "Would you like to set up AGENTS.md with project-specific rules?"
      wrapper:
        name: "GitHub Copilot Wrapper"
        description: "Create GitHub Copilot wrapper file"
        type: "copy-files"
        source: "assets/wrappers/"
        items: { "github-copilot.md": "copilot-instructions.md" }
        target: ".github/"
        required: false
        prompt: "Would you like to create a GitHub Copilot wrapper file?"
  vscode:
    name: "VSCode"
    tasks:
      vscode-xdebug:
        name: "VSCode XDebug"
        description: "Set up VSCode XDebug for PHP debugging"
        type: "copy-files"
        source: "assets/vscode"
        # Optional: specify individual files/directories to copy
        items: ["launch.json"]
        target: ".vscode/"
        required: false
        prompt: "Would you like to set up VSCode XDebug for PHP debugging?"
  windsurf:
    name: "Windsurf"
    tasks:
      rules:
        name: "Project Rules from Prompt Library"
        description: "Copy project-specific rules from Lullabot prompt library"
        type: "remote-copy-files"
        repository:
          url: "https://github.com/Lullabot/prompt_library"
          type: "branch"
          target: "main"
        source: "{project-type}/rules/"
        target: ".ai/rules"
        required: false
        requires-project: true
        prompt: "Would you like to install project-specific rules from the prompt library?"
      agents-md:
        name: "AGENTS.md"
        description: "Create/update AGENTS.md with project-specific rules"
        type: "agents-md"
        source: "assets/AGENTS.md"
        target: "."
        link-type: "markdown"
        required: false
        prompt: "Would you like to set up AGENTS.md with project-specific rules?"
      wrapper:
        name: "Windsurf Wrapper"
        description: "Create Windsurf wrapper file"
        type: "copy-files"
        source: "assets/wrappers/"
        items: { "windsurf.md": "agents.md" }
        target: ".windsurf/rules/"
        required: false
        prompt: "Would you like to create a Windsurf wrapper file?"
projects:
  development:
    name: "Development"
    validation:
      requiredFiles:
        - "composer.json"
        - ".git"
      requiredContent:
        composer.json: "drupal/core"
      optionalFiles:
        - "README.md"
        - "package.json"
        - "web/sites/default/settings.php"
  content-strategy:
    name: "Content Strategy"
  design:
    name: "Design"
  project-management:
    name: "Project Management"
  quality-assurance:
    name: "Quality Assurance"
  sales-marketing:
    name: "Sales and Marketing"
